//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TitansMVC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TitansMVC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CA requirido.
        /// </summary>
        internal static string ca_requirido {
            get {
                return ResourceManager.GetString("ca_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to campo obrigatório.
        /// </summary>
        internal static string campo_obrig {
            get {
                return ResourceManager.GetString("campo_obrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CNPJ requirido.
        /// </summary>
        internal static string cnpj_requirido {
            get {
                return ResourceManager.GetString("cnpj_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Confirmar nova senha requirido.
        /// </summary>
        internal static string confirmar_nova_senha_requirido {
            get {
                return ResourceManager.GetString("confirmar_nova_senha_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Confirmar senha requirido.
        /// </summary>
        internal static string confirmar_senha_requirido {
            get {
                return ResourceManager.GetString("confirmar_senha_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CPF requirido.
        /// </summary>
        internal static string cpf_requirido {
            get {
                return ResourceManager.GetString("cpf_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Admissão requirido.
        /// </summary>
        internal static string data_admissao_requirido {
            get {
                return ResourceManager.GetString("data_admissao_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Data Nascimento requirido.
        /// </summary>
        internal static string data_nascimento_requirido {
            get {
                return ResourceManager.GetString("data_nascimento_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo E-mail requirido.
        /// </summary>
        internal static string email_requirido {
            get {
                return ResourceManager.GetString("email_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo E-mail inválido.
        /// </summary>
        internal static string email_valido {
            get {
                return ResourceManager.GetString("email_valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Família EPI requirido.
        /// </summary>
        internal static string familia_epi_requirido {
            get {
                return ResourceManager.GetString("familia_epi_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formato inválido.
        /// </summary>
        internal static string formato_invalido {
            get {
                return ResourceManager.GetString("formato_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Marca requirido.
        /// </summary>
        internal static string marca_requirido {
            get {
                return ResourceManager.GetString("marca_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 2 caracteres.
        /// </summary>
        internal static string max_2 {
            get {
                return ResourceManager.GetString("max_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 20 caracteres.
        /// </summary>
        internal static string max_20 {
            get {
                return ResourceManager.GetString("max_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 200 caracteres.
        /// </summary>
        internal static string max_200 {
            get {
                return ResourceManager.GetString("max_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 50 caracteres.
        /// </summary>
        internal static string max_50 {
            get {
                return ResourceManager.GetString("max_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 500 caracteres.
        /// </summary>
        internal static string max_500 {
            get {
                return ResourceManager.GetString("max_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 7 caracteres.
        /// </summary>
        internal static string max_7 {
            get {
                return ResourceManager.GetString("max_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to máximo 9 caracteres.
        /// </summary>
        internal static string max_9 {
            get {
                return ResourceManager.GetString("max_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nome requirido.
        /// </summary>
        internal static string nome_requirido {
            get {
                return ResourceManager.GetString("nome_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Nova senha requirido.
        /// </summary>
        internal static string nova_senha_requirido {
            get {
                return ResourceManager.GetString("nova_senha_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Razão Social requirido.
        /// </summary>
        internal static string razao_social_requirido {
            get {
                return ResourceManager.GetString("razao_social_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Senha atual requirido.
        /// </summary>
        internal static string senha_atual_requirido {
            get {
                return ResourceManager.GetString("senha_atual_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Senha requirido.
        /// </summary>
        internal static string senha_requirido {
            get {
                return ResourceManager.GetString("senha_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Setor requirido.
        /// </summary>
        internal static string setor_requirido {
            get {
                return ResourceManager.GetString("setor_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo EPI requirido.
        /// </summary>
        internal static string tipo_epi_requirido {
            get {
                return ResourceManager.GetString("tipo_epi_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Tipo Unifore requirido.
        /// </summary>
        internal static string tipo_uniforme_requirido {
            get {
                return ResourceManager.GetString("tipo_uniforme_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Unidade de Negócio requirido.
        /// </summary>
        internal static string unidade_negocio_requirido {
            get {
                return ResourceManager.GetString("unidade_negocio_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Validade CA requirido.
        /// </summary>
        internal static string validade_ca_requirido {
            get {
                return ResourceManager.GetString("validade_ca_requirido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wait {
            get {
                object obj = ResourceManager.GetObject("Wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
